# config/routes.yaml
home:
  path:         /
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: tricks/index.html.twig
  methods: GET

show:
  path:         /show
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: tricks/show.html.twig
  methods: GET